version: '3'
 
services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    volumes_from:
      - forum:ro

  forum:
    build: forum/build
    restart: always
    image: forum 
    volumes:
      - ./forum/avatars:/var/www/dev.lesitedecuisine.fr/public/assets/avatars
      - ./forum/logs:/var/www/dev.lesitedecuisine.fr/storage/logs
    environment:
      DB_DATABASE: forum_v4
      DB_USER: forum_v4
      DB_PASSWORD_FILE: /run/secrets/db_forum_v4_password
    depends_on:
      - mariadb
    secrets:
      - db_forum_v4_password

  mariadb:
    image: mariadb:latest
    restart: always
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MARIADB_AUTO_UPGRADE: 1
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MARIADB_DATABASE: forum_v4
      MARIADB_USER: forum_v4
      MARIADB_PASSWORD_FILE: /run/secrets/db_forum_v4_password
    secrets:
      - db_root_password
      - db_forum_v4_password

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_forum_v4_password:
    file: ./secrets/db_forum_v4_password.txt
